apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-web-app-env-config
  namespace: k8s-training-apps-dev
  labels:
    app: frontend-web-app
    environment: dev
    tier: frontend
# Replace the "baseAddress" value with your https://image-proc-student-N.dev.training.oteemolabs.com
data:
  environment.json: |
    { "production": "false",
      "settings": {
                    "baseAddress":
                    "https://image-proc-student-N.dev.training.oteemolabs.com",
                    "port": "443",
                    "apiUrl": "/v0.1/pedestrian_detector",
                    "environment": "Development"
                  }
    }